import { SignalChart, type SignalField } from './SignalChart';
import { equipmentDate } from './EquipmentVerificationReport';
import { formatSignal, humanize } from '../lib/format';
import type { EquipmentEvidence } from '../lib/equipmentReview';
import { conditionSignalsFor } from '../lib/conditionSignals';

export function EquipmentOperatorEvidence({ evidence }: { evidence: EquipmentEvidence }) {
  const labels = conditionSignalsFor(evidence.alert.asset_id);
  return <div className="operator-evidence">
    <section className="production-review-card operator-trajectory"><header><div><span>Historical alert evidence</span><h2>First signal to recorded anomaly peak</h2></div><span className="production-version">{evidence.points.length.toLocaleString()} records</span></header><p>{equipmentDate(evidence.window_start)} → {equipmentDate(evidence.window_end)}. This is a recorded event window, not a live operating reading.</p><div className="operator-health-chart"><SignalChart points={evidence.points} field="anomaly_score" threshold={50} showRunStatus yPaddingRatio={0.15}/></div><ol className="operator-milestones">{evidence.transitions.map((event) => <li key={`${event.timestamp}:${event.new_state}`}><strong className={`operator-state ${event.new_state.toLowerCase()}`}>{humanize(event.new_state)}</strong><time>{equipmentDate(event.timestamp)}</time><p>{event.reason}</p></li>)}</ol></section>
    <div className="operator-signal-grid">{evidence.drivers.contributions.map((signal) => <article className="production-review-card operator-signal-card" key={signal.signal_key}><header><div><span>Condition parameter</span><h2>{labels.find((item) => item.field === signal.source_field)?.label ?? signal.signal_key}</h2></div><span className={`operator-state ${signal.engineering_state.toLowerCase()}`}>{humanize(signal.engineering_state)}</span></header><div className="operator-signal-value"><strong>{formatSignal(signal.value, 2)} <small>{signal.unit}</small></strong><span>{formatSignal(signal.contribution_percent)}% model contribution</span></div><div className="operator-variable-chart"><SignalChart points={evidence.points} field={signal.source_field as SignalField} threshold={signal.alarm_limit} showRunStatus yPaddingRatio={0.12}/></div><div className="operator-signal-reference"><span>Alarm {formatSignal(signal.alarm_limit)} · Trip {formatSignal(signal.trip_limit)} {signal.unit}</span><span>{signal.direction_of_concern === 'LOW' ? 'Below limit is concerning' : 'Above limit is concerning'}</span></div><p>Reading/contribution at {equipmentDate(evidence.drivers.as_of)} · {signal.alarm_persistence_hours} h alarm persistence at that snapshot.</p></article>)}</div>
    <section className="production-review-card operator-evidence-details"><h2>Supporting evidence and interpretation</h2><p>Review recorded findings and challenge the interpretation where your source records disagree. Missing findings are not confirmation.</p><details><summary>Lab and inspection records <span>{evidence.events.length} recorded</span></summary>{evidence.events.length ? evidence.events.map((event) => <article key={event.event_id}><span>{event.kind} · {equipmentDate(event.occurred_at)}</span><h3>{event.title}</h3><p>{event.detail}</p><p className="operator-source">Source: {event.source_reference} · {humanize(event.source_grade)}</p></article>) : <p>No finding is recorded at this cutoff. Mark supporting evidence as missing if you cannot obtain a reference.</p>}</details><details><summary>Probable explanations <span>Evidence review only</span></summary>{evidence.explanations.map((item) => <article key={item.explanation_id}><h3>{item.title} <span className={`operator-state ${item.state.toLowerCase()}`}>{humanize(item.state)}</span></h3><p>{item.starting_basis}</p>{item.supporting_events.map((event) => <p className="operator-supported" key={event.event_id}>Supports: {event.title} · {event.source_reference}</p>)}{item.challenging_events.map((event) => <p className="operator-challenged" key={event.event_id}>Challenges: {event.title} · {event.source_reference}</p>)}<p>Still needed: {item.next_check}</p></article>)}</details>{evidence.validation_note && <p className="operator-source">Data quality: {evidence.validation_note}</p>}</section>
  </div>;
}
